# Generated by Django 6.0.6 on 2026-06-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarmupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('current_day', models.IntegerField(default=1)),
                ('daily_limit', models.IntegerField(default=5)),
                ('emails_sent_today', models.IntegerField(default=0)),
                ('last_reset_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Warmup Config',
            },
        ),
    ]
