# Generated by Django 6.0.6 on 2026-06-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emaillog_click_count_emaillog_clicked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('max_attempts', models.IntegerField(default=2)),
                ('followup_days', models.CharField(default='2,5', max_length=50)),
                ('auto_reply_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Follow-up Settings',
            },
        ),
        migrations.AddField(
            model_name='emaillog',
            name='auto_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='followup_attempt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='reply_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warmupconfig',
            name='daily_limit',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='warmupconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
