# Generated by Django 6.0.6 on 2026-06-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followupsettings_emaillog_auto_replied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupsettings',
            name='test_mode',
            field=models.BooleanField(default=False),
        ),
    ]
